#include <stdio.h>
#include <string.h>
#include <getopt.h>
#include <stdlib.h>
#include <stdbool.h>

#define INTSIZE (sizeof(int) * 8)
#define SHORTSIZE (sizeof(short) * 8)
#define SEP() printf("%s# %s", RED, END)
#define USER_VALUE(x) ((int)strtol((x), NULL, 10))
#define BLUE "\e[38;5;115m"
#define END "\e[0m"
#define YELLOW "\e[38;5;99m"
#define RED "\e[38;5;70m"

void compute_bits (int, int);
void two_complement (bool *, int);
void __impl_complement (bool *, int);
void check_if_negative (int *, int, bool *);
void usage ();
void fill_array (int , bool *, int );
void handle_arguments (int , char **);
void print_result (bool *, int *, int);
void process_argument(int);

int main(int argc, char *argv[]){
	/* Converting decinals into bytes */
	if( argc == 1)
		usage();

	if(argc == 2)
		compute_bits(strtol(argv[1], NULL, 10), sizeof(int) * 8);
	else
		handle_arguments(argc, argv);

	return 0;
}

void handle_arguments(int argc, char  **argv){
	int options;
	while((options = getopt(argc, argv, "s:i:")) != -1){
		switch(options){
			case 's':
				process_argument(SHORTSIZE);
				break;
			case 'i':
				process_argument(INTSIZE);
				break;
			default:
				break;
		}
	}
}

void usage ()
{
  printf ("Usage:\n\t%s -s <number> -i <number>\n", __FILE__);
  exit (1);
}


void process_argument(int intent_size)
{
	// This was to be a macro at first
	// (BUT)
	// i find this optarg at some point somewhat hard to know where
	// it came from
	// it is brought to scope by getopt header.
	// 		char *optarg
	// 	> it is where getopt dumps whatever value it matched.
	// 	(at this time is not clear if is is static or malloced
	// 	memory)
	compute_bits(USER_VALUE(optarg), intent_size);
}

void compute_bits(int value, int size){
	bool is_negative = false;
	bool array[size] ;
	// this is an array to represent the bits
	// each byte maps to a bit
	// 	1 	0
	// 	^ 	^
	//     true    false	
	memset(array, 0, size);

	check_if_negative(&value, size, &is_negative);
	fill_array(value, array, size);

	if(is_negative)
		two_complement(array, size);

	print_result(array, &value, size);
}

void check_if_negative(int *value, int size, bool *is_negative){
	if((size / 8) == sizeof(short))
		*value = (int)((short)*value);
	if(*value < 0){
		*is_negative = true;
		 *value = -(*value);

		 /*		**NOTE**
		  * we are marking  the value as negative  and
		  * immediately converting it to a positive number
		  * 		**REASON**
		  * so as to have a single alg for populating the array
		  * and not having one for +ves and one for -ves
		  *
		  * The value is later regenerated by a two's complement
		  * on the final bits
		  */
	}
}



void fill_array(int value, bool *array, int size){
	/* This is very simple
	 * It just reverses the ides that happens when converting binary
	 * to decimal
	 * 	 1 0 0 0 1 0 1
	 * 	 ^ ^ ^ ^ ^ ^ ^
	 * 	 7 6 5 4 3 1 0
	 *		 2^7 + 2^3 + 2^1
	 *		 	^
	 *			this is what has been reverse enginered
	 */ 
	for (int i = (size - 1); i > 0; value /= 2, i--)
		array[i] = value % 2;
}

/* This handles the atual two complemnt by manipulating bits as per the
 * rule of 2's complement method or rather standard
 */
void __impl_complement(bool *array, int size){
	for(int i = size; i > 0; i--){
		if(array[i] == 1)
			array[i] = 0;
		else
			array[i] = 1;
	}
	/* signing the value as negative after neagting it
	 * this is explicit since we could just use the array to be
	 *  (i >= 0) but just to be clear i chose explicit code
	 */
	array[0] = 1;
}


void two_complement(bool *array, int size){
	/* 0 0 0 0 1 1 0 1
	 * 		 ^
	 * 		 if this value is 1 then we leave it as is and
	 * 		 proceed to toggle the rest bits
	 *
	 * 		 if that value isn't 1 then look backwards until
	 * 		 you find a 1 ->toggle all bits after that "one"
	 * 		 found
	 */	

	if(array[size - 1] == 1){
		__impl_complement(array , (size - 2));
	}else{
		for(int i = (size - 2); i > 0; i--)
			if( array[i] == 1){
				__impl_complement(array , (i - 1));
				break;
			}
	}
}

void
print_result(bool *array, int *value, int size){
	int sofar = 0;

	printf("[");
	for (int i = 0; i < size; i++)
	{
		sofar++;
		printf("%s%i%s ",YELLOW, array[i], END);
		/* This 2 blocks handle the separators the # and the
		 * space
		 * TODO intend to change it later
		 */
		if(sofar % 8 == 0 && sofar != size)
			SEP();
		if(sofar % 4 == 0 && sofar != size && sofar % 8 != 0)
			printf(" ");
	}

	printf("]\t %d\n", *value);
}
